### ISSUE TITLE
HTTP error

### ISSUE THREAD

**Issue by baseline007** [Slugger/sdepg#1]
I followed the instructions, i am using alll the latest versions, when i click on status/message in the web browser, i get this  

HTTP ERROR 500

Problem accessing /sage/sdjson/index.gsp. Reason:

    org/apache/http/client/fluent/Executor

Caused by:

java.lang.NoClassDefFoundError: org/apache/http/client/fluent/Executor
	at org.schedulesdirect.api.json.DefaultJsonRequest.submitRaw(DefaultJsonRequest.java:212)
	at org.schedulesdirect.api.json.DefaultJsonRequest.submitForJson(DefaultJsonRequest.java:135)
	at org.schedulesdirect.api.NetworkEpgClient.authorize(NetworkEpgClient.java:227)
	at org.schedulesdirect.api.NetworkEpgClient.<init>(NetworkEpgClient.java:201)
	at org.schedulesdirect.api.NetworkEpgClient.<init>(NetworkEpgClient.java:174)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	at SimpleTemplateScript1.run(SimpleTemplateScript1.groovy:100)
	at net.sf.sageplugins.webserver.groovy.templates.IncludeTemplateEngine$SimpleTemplate$1.writeTo(IncludeTemplateEngine.java:120)
	at net.sf.sageplugins.webserver.groovy.servlets.SageTemplateServlet.service(SageTemplateServlet.java:98)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:502)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:389)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:417)
	at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
	at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.handler.rewrite.RewriteHandler.handle(RewriteHandler.java:230)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:534)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:864)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:539)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:520)

**Comment by Slugger** [comment]
SageTV v9+ has native support for Schedules Direct; I would suggest heading down that road.  If you are going to continue with this plugin, this error suggests you're missing a jar file in your classpath.  Specifically the `fluent-hc` jar from Apache HttpClient.
